from pathlib import Path
import json

root = Path(__file__).resolve().parent
images_root = root / "images"
output_file = root / "question_bank.js"

category_name_map = {
    "01哲理類": "哲理類",
    "02筆畫類": "筆劃類",
    "03人身類": "人身類",
    "04字型類": "字型類",
}

code_map = {
    "01日": "A",
    "02月": "B",
    "03金": "C",
    "04木": "D",
    "05水": "E",
    "06火": "F",
    "07土": "G",
    "08竹": "H",
    "09戈": "I",
    "10十": "J",
    "11大": "K",
    "12中": "L",
    "13一": "M",
    "14弓": "N",
    "15人": "O",
    "16心": "P",
    "17手": "Q",
    "18口": "R",
    "19尸": "S",
    "20廿": "T",
    "21山": "U",
    "22女": "V",
    "23田": "W",
    "24難": "X",
    "25卜": "Y",
}

image_extensions = {"png", "jpg", "jpeg", "gif", "webp"}


def normalized_sort_key(name: str):
    # Sort using numeric prefix when available, else lexicographically.
    prefix = name.split(" ")[0]
    if prefix and prefix[0].isdigit():
        digits = ''.join(ch for ch in prefix if ch.isdigit())
        if digits:
            return (int(digits), name)
    return (9999, name)


question_bank = {}
for category_dir in sorted(images_root.iterdir(), key=lambda p: normalized_sort_key(p.name)):
    if not category_dir.is_dir():
        continue
    category_key = category_name_map.get(category_dir.name, category_dir.name)
    question_bank[category_key] = []
    for subdir in sorted(category_dir.iterdir(), key=lambda p: normalized_sort_key(p.name)):
        if not subdir.is_dir():
            continue
        code = code_map.get(subdir.name)
        if code is None:
            raise ValueError(f"Missing code mapping for subdir: {subdir}")
        files = sorted(
            [p for p in subdir.iterdir() if p.is_file() and p.suffix.lower().lstrip('.') in image_extensions],
            key=lambda p: normalized_sort_key(p.name)
        )
        for file_path in files:
            rel_path = file_path.relative_to(root).as_posix()
            question_bank[category_key].append({"img": rel_path, "code": code})

with output_file.open("w", encoding="utf-8") as f:
    f.write("// This file is generated by generate_question_bank.py\n")
    f.write("const questionBank = ")
    json.dump(question_bank, f, ensure_ascii=False, indent=4)
    f.write(";\n")

print(f"Generated {output_file} with {sum(len(v) for v in question_bank.values())} entries.")
