// This file is generated by generate_question_bank.py
const questionBank = {
    "哲理類": [
        {
            "img": "images/01哲理類/01日/01-17關.png",
            "code": "A"
        },
        {
            "img": "images/01哲理類/01日/日1-2.jpg",
            "code": "A"
        },
        {
            "img": "images/01哲理類/01日/日2-1.jpg",
            "code": "A"
        },
        {
            "img": "images/01哲理類/02月/月1-1.jpg",
            "code": "B"
        },
        {
            "img": "images/01哲理類/02月/月1-2.jpg",
            "code": "B"
        },
        {
            "img": "images/01哲理類/02月/月2-1.jpg",
            "code": "B"
        },
        {
            "img": "images/01哲理類/02月/月2-2.jpg",
            "code": "B"
        },
        {
            "img": "images/01哲理類/02月/月2-3.jpg",
            "code": "B"
        },
        {
            "img": "images/01哲理類/02月/月4-1.jpg",
            "code": "B"
        },
        {
            "img": "images/01哲理類/02月/月5-1.jpg",
            "code": "B"
        },
        {
            "img": "images/01哲理類/02月/月5-2.jpg",
            "code": "B"
        },
        {
            "img": "images/01哲理類/02月/月5-3.jpg",
            "code": "B"
        },
        {
            "img": "images/01哲理類/03金/03-03曾.png",
            "code": "C"
        },
        {
            "img": "images/01哲理類/03金/03-05只.png",
            "code": "C"
        },
        {
            "img": "images/01哲理類/03金/03-13穴.png",
            "code": "C"
        },
        {
            "img": "images/01哲理類/03金/金1-1.jpg",
            "code": "C"
        },
        {
            "img": "images/01哲理類/03金/金3-1.jpg",
            "code": "C"
        },
        {
            "img": "images/01哲理類/03金/金3-3.jpg",
            "code": "C"
        },
        {
            "img": "images/01哲理類/03金/金4-1.jpg",
            "code": "C"
        },
        {
            "img": "images/01哲理類/04木/04-04米.png",
            "code": "D"
        },
        {
            "img": "images/01哲理類/04木/04-07才.png",
            "code": "D"
        },
        {
            "img": "images/01哲理類/04木/木1-1.jpg",
            "code": "D"
        },
        {
            "img": "images/01哲理類/04木/木2-1.jpg",
            "code": "D"
        },
        {
            "img": "images/01哲理類/04木/木2-2.jpg",
            "code": "D"
        },
        {
            "img": "images/01哲理類/04木/木3-1.jpg",
            "code": "D"
        },
        {
            "img": "images/01哲理類/04木/木3-2.jpg",
            "code": "D"
        },
        {
            "img": "images/01哲理類/04木/木3-3.jpg",
            "code": "D"
        },
        {
            "img": "images/01哲理類/05水/05-06愛.png",
            "code": "E"
        },
        {
            "img": "images/01哲理類/05水/水2-2.jpg",
            "code": "E"
        },
        {
            "img": "images/01哲理類/05水/水3-1.jpg",
            "code": "E"
        },
        {
            "img": "images/01哲理類/05水/水3-2.jpg",
            "code": "E"
        },
        {
            "img": "images/01哲理類/06火/火1-2.jpg",
            "code": "F"
        },
        {
            "img": "images/01哲理類/06火/火2-2.jpg",
            "code": "F"
        },
        {
            "img": "images/01哲理類/06火/火3-2.jpg",
            "code": "F"
        },
        {
            "img": "images/01哲理類/06火/火4-1.jpg",
            "code": "F"
        },
        {
            "img": "images/01哲理類/06火/火4-2.jpg",
            "code": "F"
        },
        {
            "img": "images/01哲理類/06火/火5-1.jpg",
            "code": "F"
        },
        {
            "img": "images/01哲理類/06火/火5-2.jpg",
            "code": "F"
        },
        {
            "img": "images/01哲理類/07土/07-18美.png",
            "code": "G"
        },
        {
            "img": "images/01哲理類/07土/土1-2.jpg",
            "code": "G"
        },
        {
            "img": "images/01哲理類/07土/土2-2.jpg",
            "code": "G"
        }
    ],
    "筆劃類": [
        {
            "img": "images/02筆畫類/08竹/08-17風.png",
            "code": "H"
        },
        {
            "img": "images/02筆畫類/08竹/竹1-1.jpg",
            "code": "H"
        },
        {
            "img": "images/02筆畫類/08竹/竹1-2.jpg",
            "code": "H"
        },
        {
            "img": "images/02筆畫類/08竹/竹2-1.jpg",
            "code": "H"
        },
        {
            "img": "images/02筆畫類/08竹/竹3-1.jpg",
            "code": "H"
        },
        {
            "img": "images/02筆畫類/08竹/竹4-1.png",
            "code": "H"
        },
        {
            "img": "images/02筆畫類/09戈/戈1-1.jpg",
            "code": "I"
        },
        {
            "img": "images/02筆畫類/09戈/戈1-2.jpg",
            "code": "I"
        },
        {
            "img": "images/02筆畫類/09戈/戈2-1.jpg",
            "code": "I"
        },
        {
            "img": "images/02筆畫類/09戈/戈2-2.jpg",
            "code": "I"
        },
        {
            "img": "images/02筆畫類/09戈/戈3-1.jpg",
            "code": "I"
        },
        {
            "img": "images/02筆畫類/09戈/戈4-1.jpg",
            "code": "I"
        },
        {
            "img": "images/02筆畫類/10十/10-05求.png",
            "code": "J"
        },
        {
            "img": "images/02筆畫類/10十/10-12拜.png",
            "code": "J"
        },
        {
            "img": "images/02筆畫類/10十/10-13毋.png",
            "code": "J"
        },
        {
            "img": "images/02筆畫類/10十/十1-2.jpg",
            "code": "J"
        },
        {
            "img": "images/02筆畫類/10十/十1-4.jpg",
            "code": "J"
        },
        {
            "img": "images/02筆畫類/10十/十2-2.jpg",
            "code": "J"
        },
        {
            "img": "images/02筆畫類/11大/11-04力.png",
            "code": "K"
        },
        {
            "img": "images/02筆畫類/11大/11-13豬.png",
            "code": "K"
        },
        {
            "img": "images/02筆畫類/11大/大1-2.jpg",
            "code": "K"
        },
        {
            "img": "images/02筆畫類/11大/大2-2.jpg",
            "code": "K"
        },
        {
            "img": "images/02筆畫類/11大/大2-3.jpg",
            "code": "K"
        },
        {
            "img": "images/02筆畫類/11大/大3-1.jpg",
            "code": "K"
        },
        {
            "img": "images/02筆畫類/11大/大4-1.jpg",
            "code": "K"
        },
        {
            "img": "images/02筆畫類/12中/12-04片.png",
            "code": "L"
        },
        {
            "img": "images/02筆畫類/12中/12-06片.png",
            "code": "L"
        },
        {
            "img": "images/02筆畫類/12中/12-18買.png",
            "code": "L"
        },
        {
            "img": "images/02筆畫類/12中/中1-3.jpg",
            "code": "L"
        },
        {
            "img": "images/02筆畫類/12中/中2-1.jpg",
            "code": "L"
        },
        {
            "img": "images/02筆畫類/12中/中2-2.jpg",
            "code": "L"
        },
        {
            "img": "images/02筆畫類/12中/中4-1.jpg",
            "code": "L"
        },
        {
            "img": "images/02筆畫類/12中/中4-2.jpg",
            "code": "L"
        },
        {
            "img": "images/02筆畫類/12中/中5-1.jpg",
            "code": "L"
        },
        {
            "img": "images/02筆畫類/13一/4-1.jpg",
            "code": "M"
        },
        {
            "img": "images/02筆畫類/13一/一1-1.jpg",
            "code": "M"
        },
        {
            "img": "images/02筆畫類/13一/一2-1.jpg",
            "code": "M"
        },
        {
            "img": "images/02筆畫類/13一/一3-1.jpg",
            "code": "M"
        },
        {
            "img": "images/02筆畫類/13一/一4-2.jpg",
            "code": "M"
        },
        {
            "img": "images/02筆畫類/13一/一4-3.jpg",
            "code": "M"
        },
        {
            "img": "images/02筆畫類/13一/一5-3.jpg",
            "code": "M"
        },
        {
            "img": "images/02筆畫類/14弓/14-07了.png",
            "code": "N"
        },
        {
            "img": "images/02筆畫類/14弓/14-10你.png",
            "code": "N"
        },
        {
            "img": "images/02筆畫類/14弓/14-14弟.png",
            "code": "N"
        },
        {
            "img": "images/02筆畫類/14弓/14-16打.png",
            "code": "N"
        },
        {
            "img": "images/02筆畫類/14弓/14-21毅.png",
            "code": "N"
        },
        {
            "img": "images/02筆畫類/14弓/弓3-2.jpg",
            "code": "N"
        },
        {
            "img": "images/02筆畫類/14弓/弓3-3.jpg",
            "code": "N"
        },
        {
            "img": "images/02筆畫類/14弓/弓4-1.jpg",
            "code": "N"
        },
        {
            "img": "images/02筆畫類/14弓/弓4-2.jpg",
            "code": "N"
        },
        {
            "img": "images/02筆畫類/14弓/弓6-2.jpg",
            "code": "N"
        },
        {
            "img": "images/02筆畫類/14弓/弓6-3.jpg",
            "code": "N"
        }
    ],
    "人身類": [
        {
            "img": "images/03人身類/15人/15-10夫.png",
            "code": "O"
        },
        {
            "img": "images/03人身類/15人/人2-1.jpg",
            "code": "O"
        },
        {
            "img": "images/03人身類/15人/人2-2.jpg",
            "code": "O"
        },
        {
            "img": "images/03人身類/15人/人3-1.jpg",
            "code": "O"
        },
        {
            "img": "images/03人身類/15人/人3-2.jpg",
            "code": "O"
        },
        {
            "img": "images/03人身類/15人/人4-1.jpg",
            "code": "O"
        },
        {
            "img": "images/03人身類/15人/人5-1.jpg",
            "code": "O"
        },
        {
            "img": "images/03人身類/15人/人5-2.jpg",
            "code": "O"
        },
        {
            "img": "images/03人身類/15人/人6-1.jpg",
            "code": "O"
        },
        {
            "img": "images/03人身類/16心/16-18鄒.png",
            "code": "P"
        },
        {
            "img": "images/03人身類/16心/心1-2.jpg",
            "code": "P"
        },
        {
            "img": "images/03人身類/16心/心2-1.jpg",
            "code": "P"
        },
        {
            "img": "images/03人身類/16心/心2-2.jpg",
            "code": "P"
        },
        {
            "img": "images/03人身類/16心/心2-4.jpg",
            "code": "P"
        },
        {
            "img": "images/03人身類/16心/心2-5.jpg",
            "code": "P"
        },
        {
            "img": "images/03人身類/16心/心3-1.jpg",
            "code": "P"
        },
        {
            "img": "images/03人身類/16心/心3-2.jpg",
            "code": "P"
        },
        {
            "img": "images/03人身類/16心/心4-1.jpg",
            "code": "P"
        },
        {
            "img": "images/03人身類/16心/心5-1.jpg",
            "code": "P"
        },
        {
            "img": "images/03人身類/16心/心6-1.jpg",
            "code": "P"
        },
        {
            "img": "images/03人身類/16心/心7-2.jpg",
            "code": "P"
        },
        {
            "img": "images/03人身類/17手/17-05夫.png",
            "code": "Q"
        },
        {
            "img": "images/03人身類/17手/17-15毛.png",
            "code": "Q"
        },
        {
            "img": "images/03人身類/17手/手2-1.jpg",
            "code": "Q"
        },
        {
            "img": "images/03人身類/17手/手2-2.jpg",
            "code": "Q"
        },
        {
            "img": "images/03人身類/17手/手3-1.jpg",
            "code": "Q"
        },
        {
            "img": "images/03人身類/17手/手4-1.jpg",
            "code": "Q"
        },
        {
            "img": "images/03人身類/17手/手5-1.jpg",
            "code": "Q"
        },
        {
            "img": "images/03人身類/18口/口1-1.jpg",
            "code": "R"
        }
    ],
    "字型類": [
        {
            "img": "images/04字型類/19尸/19-09逐.png",
            "code": "S"
        },
        {
            "img": "images/04字型類/19尸/19-13放.png",
            "code": "S"
        },
        {
            "img": "images/04字型類/19尸/尸2-1.jpg",
            "code": "S"
        },
        {
            "img": "images/04字型類/19尸/尸2-2.jpg",
            "code": "S"
        },
        {
            "img": "images/04字型類/19尸/尸3-1.jpg",
            "code": "S"
        },
        {
            "img": "images/04字型類/19尸/尸4-1.jpg",
            "code": "S"
        },
        {
            "img": "images/04字型類/19尸/尸4-2.jpg",
            "code": "S"
        },
        {
            "img": "images/04字型類/19尸/尸5-1.jpg",
            "code": "S"
        },
        {
            "img": "images/04字型類/20廿/20-12曲.png",
            "code": "T"
        },
        {
            "img": "images/04字型類/20廿/20-13血.png",
            "code": "T"
        },
        {
            "img": "images/04字型類/20廿/廿1-2.jpg",
            "code": "T"
        },
        {
            "img": "images/04字型類/20廿/廿2-1.jpg",
            "code": "T"
        },
        {
            "img": "images/04字型類/20廿/廿2-2.jpg",
            "code": "T"
        },
        {
            "img": "images/04字型類/20廿/廿2-3.jpg",
            "code": "T"
        },
        {
            "img": "images/04字型類/20廿/廿3-1.jpg",
            "code": "T"
        },
        {
            "img": "images/04字型類/20廿/廿3-2.jpg",
            "code": "T"
        },
        {
            "img": "images/04字型類/20廿/廿5-1.jpg",
            "code": "T"
        },
        {
            "img": "images/04字型類/20廿/廿5-3.jpg",
            "code": "T"
        },
        {
            "img": "images/04字型類/20廿/廿6-1.jpg",
            "code": "T"
        },
        {
            "img": "images/04字型類/21山/21-04冒.png",
            "code": "U"
        },
        {
            "img": "images/04字型類/21山/21-13光.png",
            "code": "U"
        },
        {
            "img": "images/04字型類/21山/21-16屆.png",
            "code": "U"
        },
        {
            "img": "images/04字型類/21山/山3-1.jpg",
            "code": "U"
        },
        {
            "img": "images/04字型類/21山/山4-1.jpg",
            "code": "U"
        },
        {
            "img": "images/04字型類/22女/22-03紅.png",
            "code": "V"
        },
        {
            "img": "images/04字型類/22女/22-05良.png",
            "code": "V"
        },
        {
            "img": "images/04字型類/22女/22-09鼠.png",
            "code": "V"
        },
        {
            "img": "images/04字型類/22女/女2-1.jpg",
            "code": "V"
        },
        {
            "img": "images/04字型類/22女/女3-2.jpg",
            "code": "V"
        },
        {
            "img": "images/04字型類/22女/女4-2.jpg",
            "code": "V"
        },
        {
            "img": "images/04字型類/22女/女5-1.jpg",
            "code": "V"
        },
        {
            "img": "images/04字型類/22女/女5-2.jpg",
            "code": "V"
        },
        {
            "img": "images/04字型類/23田/23-12買.png",
            "code": "W"
        },
        {
            "img": "images/04字型類/23田/23-15慣.png",
            "code": "W"
        },
        {
            "img": "images/04字型類/23田/田2-1.jpg",
            "code": "W"
        },
        {
            "img": "images/04字型類/23田/田3-1.jpg",
            "code": "W"
        },
        {
            "img": "images/04字型類/24難/難1.png",
            "code": "X"
        },
        {
            "img": "images/04字型類/24難/難10.png",
            "code": "X"
        },
        {
            "img": "images/04字型類/24難/難11.png",
            "code": "X"
        },
        {
            "img": "images/04字型類/24難/難2.png",
            "code": "X"
        },
        {
            "img": "images/04字型類/24難/難3.png",
            "code": "X"
        },
        {
            "img": "images/04字型類/24難/難4.png",
            "code": "X"
        },
        {
            "img": "images/04字型類/24難/難5.png",
            "code": "X"
        },
        {
            "img": "images/04字型類/24難/難6.png",
            "code": "X"
        },
        {
            "img": "images/04字型類/24難/難7.png",
            "code": "X"
        },
        {
            "img": "images/04字型類/24難/難8.png",
            "code": "X"
        },
        {
            "img": "images/04字型類/24難/難9.png",
            "code": "X"
        },
        {
            "img": "images/04字型類/25卜/25-02亡.png",
            "code": "Y"
        },
        {
            "img": "images/04字型類/25卜/25-10鼠.png",
            "code": "Y"
        },
        {
            "img": "images/04字型類/25卜/25-21悔.png",
            "code": "Y"
        },
        {
            "img": "images/04字型類/25卜/卜1-1.jpg",
            "code": "Y"
        },
        {
            "img": "images/04字型類/25卜/卜3-1.jpg",
            "code": "Y"
        },
        {
            "img": "images/04字型類/25卜/卜4-1.jpg",
            "code": "Y"
        }
    ]
};
